./include/define.svh
./duv/AXI/Read_Arbiter.sv
./duv/AXI/Read_Address_Channel.sv
./duv/AXI/Read_Data_Channel.sv
./duv/AXI/Write_Data_Channel.sv
./duv/AXI/Write_Response_Channel.sv
./duv/AXI/Write_Address_Channel.sv
./duv/AXI/Write_Arbiter.sv
./duv/AXI/AXI.sv
./duv/SRAM.v
./duv/SRAM_wrapper.sv

./SRAM_tb.sv
./uvm/interface.sv
./uvm/transaction.sv
./uvm/sequence.sv
./uvm/driver.sv
./uvm/monitor.sv
./uvm/scoreboard.sv
./uvm/agent.sv
./uvm/referenceModel.sv
./uvm/environment.sv
./uvm/test.sv
